version: '3.8'

services:
  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - sena-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - sena-network

networks:
  sena-network:
    driver: bridge